### ISSUE TITLE
Clean up files

### ISSUE THREAD

**Issue by edgabaldi** [artciclo/url-shorter-challenge-arthur#1]
## Some initial improvements to do

* There is no reason to have the files `Express.js` and `readme` in this repository.
* We could also separate the webapp to another repository. To test the api we will use the insomnia.
* I missed the package.json file where we add the project dependencies and other tasks.
* Create a `src` folder on the root of repository and move the code to there. The `package.json` file will be outside.

What do you think?

**Comment by artciclo** [comment]
- There is no reason to have the files Express.js and readme in this repository.
 file readme was renamed to notes.txt (and added to .gitignore)

- We could also separate the webapp to another repository. To test the api we will use the insomnia.
I created (clone) another reopository to organize that. 

- I missed the package.json file where we add the project dependencies and other tasks.
file was created and updated 
- Create a src folder on the root of repository and move the code to there. The package.json file will be outside.
 /src created
 
What do you think?
Looks a great sugestion.
now I will try to use insomnia and find the bugs there maybe was created 
-To test the api we will use the insomnia.
